### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by DCastellacci** [Malanche/escpospp#2]
Accents

Hello,

I am French
I have a problem with the accents é è ô currency symbol (€)
when I print I have strange characters
for example in french quantité english quantity
quantité takes an accent (é) quantit(é) quantité

Can you help me

thank you

Didier Castellacci

**Comment by birkbak** [comment]
you can escape special chars with \xnn where n is between 0-f
with the default char set you can type 
é = \x82
è = \x8a
ô = \x93
but not the euro char. 
you can find more info about char settings here
[epson's site](https://reference.epson-biz.com/modules/ref_charcode_en/index.php)

**Comment by DCastellacci** [comment]
With the Epson Tm T20II terminal there is a solution to have all the accents in French as well as the currency symbol
1) you have to download the epson TM T20II utility which is: TM-T20IIUtility120.exe install on windows 10 and connect your terminal tm t20II by usb connection to windows start the utility choose policy Europe then France code page cp858 or pc858 it's like

2) under ubuntu 18.10 connect your TM T20II terminal to usb then do:

in a terminal

sudo usermod -a -G lp username 
and reboot


in a terminal

echo -e "ééééééèèèèè àààààà €€€€" | file -
/dev/stdin: UTF-8 Unicode text


OK
echo -e "ééééééèèèèè àààààà €€€€" | iconv -f UTF-8 -t CP858 > /dev/usb/lp0

use the utility under ubuntu 18.10 iconv

Usage: iconv [OPTION...] [FILE...]
Convert encoding of given files from one encoding to another.

follow the example above

iconv is compatible with c ++ iconv.h

Thank You 
Didier
